In [1]:
from importlib import reload
import are_you_the_one as ayto
from data_reader import Reader
import pandas as pd
import numpy as np

In [2]:
N = 10
M = ayto.Matrix(N)

In [3]:
M.shape

(3628800, 10)

In [4]:
M[:10]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 9, 8],
       [0, 1, 2, 3, 4, 5, 6, 8, 7, 9],
       [0, 1, 2, 3, 4, 5, 6, 8, 9, 7],
       [0, 1, 2, 3, 4, 5, 6, 9, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 9, 8, 7],
       [0, 1, 2, 3, 4, 5, 7, 6, 8, 9],
       [0, 1, 2, 3, 4, 5, 7, 6, 9, 8],
       [0, 1, 2, 3, 4, 5, 7, 8, 6, 9],
       [0, 1, 2, 3, 4, 5, 7, 8, 9, 6]], dtype=int8)

In [5]:
reader = Reader(1)

In [6]:
reader.cast

cast_member  age               hometown     sex  season  \
0                  Adam Kuhn   24     Sterling, Virginia    Male       1   
1        Andrean "Dre" McCoy   23       Atlanta, Georgia    Male       1   
2                Chris Scali   24     Brooklyn, New York    Male       1   
3             Chris Tolleson   23         Virginia Beach    Male       1   
4              Dillan Ostrom   23   Finley, North Dakota    Male       1   
5              Ethan Diamond   23       Denver, Colorado    Male       1   
6                Joey Dillon   23       Atlanta, Georgia    Male       1   
7           John "JJ" Jacobs   25         Washington, DC    Male       1   
8                Ryan Malaty   24      Greeley, Colorado    Male       1   
9       Wesley "Wes" Buckles   25       Phoenix, Arizona    Male       1   
10                 Amber Lee   22          Austin, Texas  Female       1   
11          Ashleigh Feaster   23            Akron, Ohio  Female       1   
12       Brittany Baldassari   24  Boston, Massachusetts  Female       1   
13         Coleysia Chestnut   23         Selma, Alabama  Female       1   
14  Jacinda "Jacy" Rodriguez   24  Carolina, Puerto Rico  Female       1   
15             Jessica Perez   23         Miami, Florida  Female       1   
16               Kayla Lusby   22  Greenfield, Tennessee  Female       1   
17             Paige Brendel   22       Phoenix, Arizona  Female       1   
18           Shanley McIntee   24     Mishawaka, Indiana  Female       1   
19              Simone Kelly   23       Atlanta, Georgia  Female       1   

    nickname  
0       Adam  
1        Dre  
2   Chris S.  
3   Chris T.  
4     Dillan  
5      Ethan  
6       Joey  
7       John  
8       Ryan  
9        Wes  
10     Amber  
11  Ashleigh  
12  Brittany  
13  Coleysia  
14      Jacy  
15   Jessica  
16     Kayla  
17     Paige  
18   Shanley  
19    Simone

In [9]:
guys_list = reader.cast.query("sex == 'Male'")['nickname'].tolist()
guys = {i: ayto.Guy(nickname) for i, nickname in enumerate(guys_list)}
rev_guys = {guy: i for i, guy in guys.items()}
for i, guy in guys.items():
    print(i, guy, rev_guys[guy])

0 Adam 0
1 Dre 1
2 Chris S. 2
3 Chris T. 3
4 Dillan 4
5 Ethan 5
6 Joey 6
7 John 7
8 Ryan 8
9 Wes 9


In [11]:
girls_list = reader.cast.query("sex == 'Female'")['nickname'].tolist()
girls = {i: ayto.Girl(nickname) for i, nickname in enumerate(girls_list)}
rev_girls = {girl: i for i, girl in girls.items()}
for j, girl in girls.items():
    print(j, girl, rev_girls[girl])

0 Amber 0
1 Ashleigh 1
2 Brittany 2
3 Coleysia 3
4 Jacy 4
5 Jessica 5
6 Kayla 6
7 Paige 7
8 Shanley 8
9 Simone 9


In [ ]:
ceremony1 = reader.progress.query("ceremony == 1")[['guy', 'girl', 'status']]
ceremony1

guy      girl                     status
0       Adam  Brittany                Not A Match
9   Chris S.  Ashleigh                Not A Match
18  Chris T.   Jessica                Not A Match
27    Dillan  Coleysia  Unconfirmed Perfect Match
36       Dre      Jacy                Not A Match
45     Ethan   Shanley                Not A Match
54      John    Simone                Not A Match
63      Joey     Paige                Not A Match
72      Ryan     Amber                Not A Match
81       Wes     Kayla  Unconfirmed Perfect Match

In [ ]:
iter_couples = zip(ceremony1.guy.map(rev_guys).rename('guy_idx'),
                   ceremony1.girl.map(rev_girls).rename('girl_idx'))
p = {tuple([guy, girl]) for guy, girl in iter_couples}
path = ayto.Path(p)
path

Path({(2, 1), (4, 3), (5, 8), (9, 6), (1, 4), (8, 0), (7, 9), (6, 7), (0, 2), (3, 5)})

In [ ]:
for match in path:
    print(match)

(2, 1)
(4, 3)
(5, 8)
(9, 6)
(1, 4)
(8, 0)
(7, 9)
(6, 7)
(0, 2)
(3, 5)


In [ ]:
np_path = np.array([m[1] for m in sorted(path.matches, key=lambda x: x[0])],
                   dtype=np.int8)
np_path

array([2, 4, 1, 5, 3, 8, 7, 9, 0, 6], dtype=int8)

In [ ]:
M.shape

(3628800, 10)

In [ ]:
# compare the path with each row in the matrix M
mask = np.equal(M[:], np_path, dtype=np.bool_)
mask.all(axis=1).sum()


1

In [ ]:
idx = np.argwhere(mask.all(axis=1)).flatten()
M[idx], np_path

(array([[2, 4, 1, 5, 3, 8, 7, 9, 0, 6]], dtype=int8),
 array([2, 4, 1, 5, 3, 8, 7, 9, 0, 6], dtype=int8))